export const ProductData = [
  {
    id: 1,
    product_name: "Nganji Cheddar Cheese",
    slug: "nganji-cheddar-cheese",
    label_type: "Gouda Cheese",
    weight: "1kg",
    company_name: "GISHWATI FARMS LTD",
    location: {
      district: "Rulindo",
      sector: "Dairy products and eggs",
    },
    contact: {
      phone: "0788 465 258",
      email: "kageruka10emmanuel100@gmail.com",
    },
    classification: {
      cluster: "Agro-Processing",
      license_no: "038/RSB/DG/NCD/MLI/22-23",
    },
    status_info: {
      approval_date: "2022-12-31",
      expiry_date: "2026-04-19",
      validity_status: "Valid",
    },
    image_url: "/Products/product01.png",
  },
  {
    id: 2,
    product_name: "Dodoma Lala salama Mattress",
    slug: "dodoma-lala-salama-mattress",
    label_type: "Foam Mattress",
    weight: "25kg",
    company_name: "VIVA PRODUCTS LTD",
    location: {
      district: "Gasabo",
      sector: "Furniture",
    },
    contact: {
      phone: "0787240745",
      email: "ali@ramawa.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "003/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2020-09-30",
      expiry_date: "2021-09-30",
      validity_status: "Expired",
    },
    image_url: "/Products/product02.png",
  },
  {
    id: 3,
    product_name: "Dodoma Prestige Quilted Mattress",
    slug: "dodoma-prestige-quilted-mattress",
    label_type: "Quilted",
    weight: "30kg",
    company_name: "VIVA PRODUCTS LTD",
    location: {
      district: "Gasabo",
      sector: "Furniture",
    },
    contact: {
      phone: "0787240745",
      email: "ali@ramawa.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "004/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2020-09-30",
      expiry_date: "2021-09-30",
      validity_status: "Expired",
    },
    image_url: "/Products/product03.png",
  },
  {
    id: 4,
    product_name: "Paints",
    slug: "paints",
    label_type: "Emulsion",
    weight: "20L",
    company_name: "AMACO PAINTS Ltd",
    location: {
      district: "Kicukiro",
      sector: "Paints and primers and finishes",
    },
    contact: {
      phone: "0788301525",
      email: "amacopaints1@gmail.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "085/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2023-09-30",
      expiry_date: "2025-09-30",
      validity_status: "Expired",
    },
    image_url: "/Products/product04.png",
  },
  {
    id: 5,
    product_name: "Amaco paints",
    slug: "amaco-paints",
    label_type: "Gloss",
    weight: "5L",
    company_name: "AMACO PAINTS Ltd",
    location: {
      district: "Kicukiro",
      sector: "Paints and primers and finishes",
    },
    contact: {
      phone: "0788301525",
      email: "amacopaints1@gmail.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "085/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2022-09-30",
      expiry_date: "2025-09-30",
      validity_status: "Expired",
    },
    image_url: "/Products/product05.png",
  },
  {
    id: 6,
    product_name: "Amaco paints Wood Finish",
    slug: "amaco-paints-wood",
    label_type: "Varnish",
    weight: "4L",
    company_name: "AMACO PAINTS Ltd",
    location: {
      district: "Kicukiro",
      sector: "Paints and primers and finishes",
    },
    contact: {
      phone: "0788301525",
      email: "amacopaints1@gmail.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "085/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2022-09-30",
      expiry_date: "2025-09-30",
      validity_status: "Expired",
    },
    image_url: "/Products/product07.png",
  },
  {
    id: 7,
    product_name: "Amaco paints NC Varnish",
    slug: "amaco-paints-nc",
    label_type: "Industrial",
    weight: "1L",
    company_name: "AMACO PAINTS Ltd",
    location: {
      district: "Kicukiro",
      sector: "Paints and primers and finishes",
    },
    contact: {
      phone: "0788301525",
      email: "amacopaints1@gmail.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "085/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2022-09-30",
      expiry_date: "2025-09-30",
      validity_status: "Expired",
    },
    image_url: "/Products/product08.png",
  },
  {
    id: 8,
    product_name: "Amaco paints Weather Gaurd",
    slug: "amaco-paints-weather-guard",
    label_type: "Exterior",
    weight: "20L",
    company_name: "AMACO PAINTS Ltd",
    location: {
      district: "Kicukiro",
      sector: "Paints and primers and finishes",
    },
    contact: {
      phone: "0788301525",
      email: "amacopaints1@gmail.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "085/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2022-09-30",
      expiry_date: "2025-09-30",
      validity_status: "Expired",
    },
    image_url: "/Products/product09.png",
  },
  {
    id: 9,
    product_name: "Yogurt",
    slug: "yogurt",
    label_type: "Masaka Farms Greek",
    weight: "500g",
    company_name: "Masaka Farms Ltd",
    location: {
      district: "Kicukiro",
      sector: "Dairy Products",
    },
    contact: {
      phone: "0788 123 456",
      email: "info@masakafarms.rw",
    },
    classification: {
      cluster: "Agro-Processing",
      license_no: "012/RSB/DG/2024",
    },
    status_info: {
      approval_date: "2024-01-15",
      expiry_date: "2027-01-15",
      validity_status: "Valid",
    },
    image_url: "/FeaturesProduct/image01.png",
  },
  {
    id: 10,
    product_name: "Cheese",
    slug: "cheese",
    label_type: "Nganji Mozzarella Cheese",
    weight: "200g",
    company_name: "Nganji Dairy Ltd",
    location: {
      district: "Musanze",
      sector: "Dairy Products",
    },
    contact: {
      phone: "0788 999 888",
      email: "contact@nganjidairy.com",
    },
    classification: {
      cluster: "Agro-Processing",
      license_no: "045/RSB/DG/2023",
    },
    status_info: {
      approval_date: "2023-05-20",
      expiry_date: "2026-05-20",
      validity_status: "Valid",
    },
    image_url: "/FeaturesProduct/image02.png",
  },
  {
    id: 11,
    product_name: "Honey",
    slug: "honey",
    label_type: "Pure Honey",
    weight: "1kg",
    company_name: "Rwanda Beekeepers Coop",
    location: {
      district: "Nyabihu",
      sector: "Pure Honey",
    },
    contact: {
      phone: "0785 000 111",
      email: "honey@beekeepers.rw",
    },
    classification: {
      cluster: "Agro-Processing",
      license_no: "099/RSB/DG/2022",
    },
    status_info: {
      approval_date: "2022-11-10",
      expiry_date: "2025-11-10",
      validity_status: "Valid",
    },
    image_url: "/FeaturesProduct/image03.png",
  },
  {
    id: 12,
    product_name: "Pineapple juice",
    slug: "pineapple-juice",
    label_type: "Inyange Pineapple",
    weight: "1L",
    company_name: "Inyange Industries Ltd",
    location: {
      district: "Gasabo",
      sector: "Beverages",
    },
    contact: {
      phone: "0788 300 000",
      email: "info@inyangeindustries.com",
    },
    classification: {
      cluster: "Agro-Processing",
      license_no: "001/RSB/DG/2021",
    },
    status_info: {
      approval_date: "2021-08-15",
      expiry_date: "2026-08-15",
      validity_status: "Valid",
    },
    image_url: "/FeaturesProduct/image04.png",
  },
  {
    id: 13,
    product_name: "Amaco paints Premium",
    slug: "amaco-paints-premium",
    label_type: "Premium Matte",
    weight: "10L",
    company_name: "AMACO PAINTS Ltd",
    location: {
      district: "Kicukiro",
      sector: "Paints and primers and finishes",
    },
    contact: {
      phone: "0788301525",
      email: "amacopaints1@gmail.com",
    },
    classification: {
      cluster: "Light Manufacturing",
      license_no: "085/RSB/DG/NCD/MLI/20-21",
    },
    status_info: {
      approval_date: "2022-09-30",
      expiry_date: "2025-09-30",
      validity_status: "Expired",
    },
    image_url: "/FeaturesProduct/image05.png",
  },
];
