import { Potta_One, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Implementer from "@/components/Implementer";
import Script from "next/script";

const pottaOne = Potta_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-potta",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Made in Rwanda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pottaOne.variable} ${poppins.variable} antialiased`}>
        <Navbar />
        {children}
        <Implementer />
        <Footer />
      </body>
    </html>
  );
}
